"""Add tier to billing_subscriptions

Razorpay plan IDs are generated by Razorpay (`plan_<random>`) and cannot be
chosen by the merchant, so deriving the tier from the plan ID substring is not
reliable. Store the tier chosen at subscribe time instead.

Revision ID: 017_billing_tier
Revises: 416ec8b97cf7
Create Date: 2026-10-01 00:00:00.000000
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "017_billing_tier"
down_revision: str | Sequence[str] | None = "416ec8b97cf7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "billing_subscriptions",
        sa.Column("tier", sa.String(), nullable=True),
    )
    # Existing rows: derive once from the plan ID so historical subscriptions
    # keep whatever entitlement they were granted. Free is the safe default
    # when the plan ID carries no recognisable tier.
    op.execute(
        """
        UPDATE billing_subscriptions
        SET tier = CASE
            WHEN LOWER(plan_id) LIKE '%pro%' THEN 'pro'
            WHEN LOWER(plan_id) LIKE '%team%' THEN 'team'
            ELSE 'free'
        END
        WHERE tier IS NULL
        """
    )


def downgrade() -> None:
    op.drop_column("billing_subscriptions", "tier")
