"""Add UsageMeter for quotas

Revision ID: 416ec8b97cf7
Revises: ad2f94f54aa7
Create Date: 2026-09-30 21:39:31.933719
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "416ec8b97cf7"
down_revision: str | Sequence[str] | None = "ad2f94f54aa7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_meters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("inspections_count", sa.Integer(), nullable=False),
        sa.Column("llm_inspections_count", sa.Integer(), nullable=False),
        sa.Column("api_calls_count", sa.Integer(), nullable=False),
        sa.Column("bandwidth_bytes", sa.Integer(), nullable=False),
        sa.Column("inspections_limit", sa.Integer(), nullable=False),
        sa.Column("llm_inspections_limit", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usage_meters_period"), "usage_meters", ["period"], unique=False)
    op.create_index(
        op.f("ix_usage_meters_workspace_id"), "usage_meters", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_meters_workspace_id"), table_name="usage_meters")
    op.drop_index(op.f("ix_usage_meters_period"), table_name="usage_meters")
    op.drop_table("usage_meters")
    # ### end Alembic commands ###
