"""Add BillingSubscription for Razorpay

Revision ID: ad2f94f54aa7
Revises: 016
Create Date: 2026-09-30 21:34:53.848093
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "ad2f94f54aa7"
down_revision: str | Sequence[str] | None = "016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_subscriptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("razorpay_customer_id", sa.String(), nullable=True),
        sa.Column("razorpay_subscription_id", sa.String(), nullable=True),
        sa.Column("plan_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_subscriptions_account_id"),
        "billing_subscriptions",
        ["account_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_rate_limit_counters_updated_at"), table_name="rate_limit_counters")
    op.drop_table("rate_limit_counters")
    op.drop_index(op.f("ix_account_workspaces_unique"), table_name="account_workspaces")
    op.alter_column(
        "agent_permissions",
        "task_type",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "agent_permissions",
        "allowed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "agent_spend_limits",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "agent_spend_limits",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "agents", "name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "agents",
        "api_key_hash",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "agents",
        "status",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=True,
        existing_server_default=sa.text("'active'::text"),
    )
    op.alter_column(
        "agents",
        "capabilities",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "agents",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_constraint(op.f("agents_workspace_id_name_key"), "agents", type_="unique")
    op.drop_constraint(op.f("ck_agents_status"), "agents", type_="check")
    op.alter_column(
        "audit_logs", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.drop_index(op.f("ix_audit_logs_workspace_created"), table_name="audit_logs")
    op.alter_column(
        "custom_roles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_constraint(op.f("cve_cache_cve_id_key"), "cve_cache", type_="unique")
    op.drop_index(op.f("ix_cve_cache_cve_id"), table_name="cve_cache")
    op.create_index(op.f("ix_cve_cache_cve_id"), "cve_cache", ["cve_id"], unique=True)
    op.alter_column(
        "data_retention_policies",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "data_retention_policies",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_index(op.f("idx_delegation_chains_task"), table_name="delegation_chains")
    op.drop_index(op.f("idx_delegation_chains_workspace"), table_name="delegation_chains")
    op.drop_index(op.f("ix_dlp_policies_class_destination"), table_name="dlp_policies")
    op.alter_column(
        "ip_allowlist_entries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "memory_entries",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("ix_memory_entries_workspace_id"), table_name="memory_entries")
    op.create_index(
        op.f("ix_memory_retrieval_log_created_at"),
        "memory_retrieval_log",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "network_access_rules",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "policy_rules", "name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "policy_rules",
        "task_type",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "policy_rules",
        "action",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_policy_rules_workspace_priority"), table_name="policy_rules")
    op.drop_constraint(op.f("ck_policy_rules_action"), "policy_rules", type_="check")
    op.drop_index(op.f("idx_resource_permissions_agent"), table_name="resource_permissions")
    op.alter_column(
        "review_items",
        "review_token",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "review_items",
        "status",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=True,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.alter_column(
        "review_items",
        "on_expire",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=True,
        existing_server_default=sa.text("'block'::text"),
    )
    op.drop_constraint(op.f("ck_review_items_on_expire"), "review_items", type_="check")
    op.drop_constraint(op.f("ck_review_items_status"), "review_items", type_="check")
    op.alter_column(
        "scim_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "spend_ledger",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "task_schemas",
        "task_type",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "task_schemas",
        "version",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=True,
        existing_server_default=sa.text("'v1'::text"),
    )
    op.drop_constraint(
        op.f("task_schemas_workspace_id_task_type_version_key"), "task_schemas", type_="unique"
    )
    op.alter_column(
        "tasks",
        "depth",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "tasks", "task_type", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "tasks",
        "schema_version",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=True,
        existing_server_default=sa.text("'v1'::text"),
    )
    op.alter_column(
        "tasks", "payload_hash", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "tasks",
        "risk_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("0.0"),
    )
    op.alter_column(
        "tasks", "decision", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "tasks", "groq_model", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    op.alter_column(
        "tasks", "trace_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    op.alter_column(
        "tasks", "span_id", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    op.drop_index(op.f("idx_tasks_decision"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_parent"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_root"), table_name="tasks")
    op.drop_index(op.f("idx_tasks_workspace"), table_name="tasks")
    op.drop_constraint(op.f("ck_tasks_decision"), "tasks", type_="check")
    op.drop_index(op.f("idx_telemetry_events_sender"), table_name="telemetry_events")
    op.drop_index(op.f("idx_telemetry_events_type"), table_name="telemetry_events")
    op.drop_index(op.f("idx_telemetry_events_workspace"), table_name="telemetry_events")
    op.alter_column(
        "trace_events",
        "trace_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "trace_events",
        "span_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "trace_events",
        "parent_span_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "trace_events",
        "event_name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "trace_events",
        "attributes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("idx_trace_events_trace_id"), table_name="trace_events")
    op.alter_column(
        "violations", "layer", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "violations",
        "violation_type",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "violations",
        "severity",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "violations",
        "resolved_by",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_violations_task"), table_name="violations")
    op.drop_index(op.f("idx_violations_workspace"), table_name="violations")
    op.drop_constraint(op.f("ck_violations_layer"), "violations", type_="check")
    op.drop_constraint(op.f("ck_violations_severity"), "violations", type_="check")
    op.alter_column(
        "workspace_members",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "workspace_members",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "workspace_spend_limits",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "workspace_spend_limits",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "workspaces", "name", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=False
    )
    op.alter_column(
        "workspaces",
        "admin_email",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "workspaces",
        "api_key_hash",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "workspaces",
        "fail_mode",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=True,
        existing_server_default=sa.text("'closed'::text"),
    )
    op.alter_column(
        "workspaces",
        "groq_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("0.3"),
    )
    op.alter_column(
        "workspaces",
        "block_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("0.8"),
    )
    op.alter_column(
        "workspaces",
        "review_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'0.5'::double precision"),
    )
    op.alter_column(
        "workspaces",
        "default_deny",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "workspaces",
        "ips_mode",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'block'::character varying"),
    )
    op.drop_constraint(op.f("ck_workspaces_fail_mode"), "workspaces", type_="check")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_workspaces_fail_mode"),
        "workspaces",
        "fail_mode = ANY (ARRAY['open'::text, 'closed'::text])",
    )
    op.alter_column(
        "workspaces",
        "ips_mode",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'block'::character varying"),
    )
    op.alter_column(
        "workspaces",
        "default_deny",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "workspaces",
        "review_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'0.5'::double precision"),
    )
    op.alter_column(
        "workspaces",
        "block_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("0.8"),
    )
    op.alter_column(
        "workspaces",
        "groq_threshold",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("0.3"),
    )
    op.alter_column(
        "workspaces",
        "fail_mode",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'closed'::text"),
    )
    op.alter_column(
        "workspaces",
        "api_key_hash",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "workspaces",
        "admin_email",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "workspaces", "name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "workspace_spend_limits",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "workspace_spend_limits",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "workspace_members",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "workspace_members",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_check_constraint(
        op.f("ck_violations_severity"),
        "violations",
        "severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])",
    )
    op.create_check_constraint(
        op.f("ck_violations_layer"),
        "violations",
        "layer = ANY (ARRAY['schema'::text, 'rule'::text, 'semantic'::text, 'policy'::text, 'identity'::text, 'delegation'::text, 'preflight'::text, 'cve'::text, 'ips'::text, 'compliance'::text])",
    )
    op.create_index(
        op.f("idx_violations_workspace"),
        "violations",
        ["workspace_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("idx_violations_task"), "violations", ["task_id"], unique=False)
    op.alter_column(
        "violations",
        "resolved_by",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "violations",
        "severity",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "violations",
        "violation_type",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "violations", "layer", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.create_index(op.f("idx_trace_events_trace_id"), "trace_events", ["trace_id"], unique=False)
    op.alter_column(
        "trace_events",
        "attributes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "trace_events",
        "event_name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "trace_events",
        "parent_span_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "trace_events",
        "span_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "trace_events",
        "trace_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("idx_telemetry_events_workspace"),
        "telemetry_events",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_telemetry_events_type"), "telemetry_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("idx_telemetry_events_sender"), "telemetry_events", ["sender_agent_id"], unique=False
    )
    op.create_check_constraint(
        op.f("ck_tasks_decision"),
        "tasks",
        "decision = ANY (ARRAY['allow'::text, 'block'::text, 'review'::text, 'error'::text])",
    )
    op.create_index(
        op.f("idx_tasks_workspace"),
        "tasks",
        ["workspace_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("idx_tasks_root"), "tasks", ["root_task_id"], unique=False)
    op.create_index(op.f("idx_tasks_parent"), "tasks", ["parent_task_id"], unique=False)
    op.create_index(op.f("idx_tasks_decision"), "tasks", ["workspace_id", "decision"], unique=False)
    op.alter_column(
        "tasks", "span_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column(
        "tasks", "trace_id", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column(
        "tasks", "groq_model", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column(
        "tasks", "decision", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "tasks",
        "risk_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("0.0"),
    )
    op.alter_column(
        "tasks", "payload_hash", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "tasks",
        "schema_version",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'v1'::text"),
    )
    op.alter_column(
        "tasks", "task_type", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "tasks",
        "depth",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.create_unique_constraint(
        op.f("task_schemas_workspace_id_task_type_version_key"),
        "task_schemas",
        ["workspace_id", "task_type", "version"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "task_schemas",
        "version",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'v1'::text"),
    )
    op.alter_column(
        "task_schemas",
        "task_type",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "spend_ledger",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "scim_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_check_constraint(
        op.f("ck_review_items_status"),
        "review_items",
        "status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'expired'::text])",
    )
    op.create_check_constraint(
        op.f("ck_review_items_on_expire"),
        "review_items",
        "on_expire = ANY (ARRAY['allow'::text, 'block'::text])",
    )
    op.alter_column(
        "review_items",
        "on_expire",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'block'::text"),
    )
    op.alter_column(
        "review_items",
        "status",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'pending'::text"),
    )
    op.alter_column(
        "review_items",
        "review_token",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("idx_resource_permissions_agent"),
        "resource_permissions",
        ["agent_id", "resource_type", "action"],
        unique=False,
    )
    op.create_check_constraint(
        op.f("ck_policy_rules_action"),
        "policy_rules",
        "action = ANY (ARRAY['allow'::text, 'block'::text, 'review'::text, 'flag'::text])",
    )
    op.create_index(
        op.f("idx_policy_rules_workspace_priority"),
        "policy_rules",
        ["workspace_id", "priority"],
        unique=False,
    )
    op.alter_column(
        "policy_rules",
        "action",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "policy_rules",
        "task_type",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "policy_rules", "name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "network_access_rules",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index(op.f("ix_memory_retrieval_log_created_at"), table_name="memory_retrieval_log")
    op.create_index(
        op.f("ix_memory_entries_workspace_id"), "memory_entries", ["workspace_id"], unique=False
    )
    op.alter_column(
        "memory_entries",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "ip_allowlist_entries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_index(
        op.f("ix_dlp_policies_class_destination"),
        "dlp_policies",
        ["workspace_id", "data_class", "destination"],
        unique=False,
    )
    op.create_index(
        op.f("idx_delegation_chains_workspace"),
        "delegation_chains",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_delegation_chains_task"), "delegation_chains", ["task_id"], unique=False
    )
    op.alter_column(
        "data_retention_policies",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "data_retention_policies",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index(op.f("ix_cve_cache_cve_id"), table_name="cve_cache")
    op.create_index(op.f("ix_cve_cache_cve_id"), "cve_cache", ["cve_id"], unique=False)
    op.create_unique_constraint(
        op.f("cve_cache_cve_id_key"), "cve_cache", ["cve_id"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "custom_roles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_index(
        op.f("ix_audit_logs_workspace_created"),
        "audit_logs",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.alter_column(
        "audit_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_check_constraint(
        op.f("ck_agents_status"),
        "agents",
        "status = ANY (ARRAY['active'::text, 'suspended'::text])",
    )
    op.create_unique_constraint(
        op.f("agents_workspace_id_name_key"),
        "agents",
        ["workspace_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "agents",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "agents",
        "capabilities",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "agents",
        "status",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
        existing_server_default=sa.text("'active'::text"),
    )
    op.alter_column(
        "agents",
        "api_key_hash",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "agents", "name", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "agent_spend_limits",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "agent_spend_limits",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "agent_permissions",
        "allowed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "agent_permissions",
        "task_type",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_account_workspaces_unique"),
        "account_workspaces",
        ["account_id", "workspace_id"],
        unique=True,
    )
    op.create_table(
        "rate_limit_counters",
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "window_start", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column(
            "count", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("rate_limit_counters_pkey")),
    )
    op.create_index(
        op.f("ix_rate_limit_counters_updated_at"),
        "rate_limit_counters",
        ["updated_at"],
        unique=False,
    )
    op.drop_index(op.f("ix_billing_subscriptions_account_id"), table_name="billing_subscriptions")
    op.drop_table("billing_subscriptions")
    # ### end Alembic commands ###
