"""Systemd unit rendering for the A2A Firewall proxy daemon.

Produces a ``systemd`` service unit that runs the proxy invisibly in the
background, installs the OS CA trust, and exports the relevant trust env vars
so every process on the machine trusts the local Root CA.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from a2a_firewall.egress_guard.transparent_redirect import A2A_FWMARK


@dataclass
class SystemdUnit:
    """Renders a deterministic systemd unit file string."""

    description: str = "A2A Firewall Transparent Proxy Daemon"
    exec_path: str = "a2a-proxy"
    args: list[str] = field(default_factory=lambda: ["daemon"])
    user: str = "root"
    restarts: str = "on-failure"
    restart_sec: str = "5"
    ca_cert_path: str = "/usr/local/share/ca-certificates/a2a-root.crt"
    fwmark: int = A2A_FWMARK
    redirect_enabled: bool = True
    inspect_enabled: bool = False

    @property
    def environment_lines(self) -> str:
        lines = [
            f"SSL_CERT_FILE={self.ca_cert_path}",
            f"REQUESTS_CA_BUNDLE={self.ca_cert_path}",
            f"CURL_CA_BUNDLE={self.ca_cert_path}",
            "NODE_EXTRA_CA_CERTS=" + self.ca_cert_path,
            f"A2A_FW_MARK=0x{self.fwmark:x}",
            f"A2A_REDIRECT_ENABLED={'1' if self.redirect_enabled else '0'}",
            f"A2A_INSPECT_ENABLED={'1' if self.inspect_enabled else '0'}",
        ]
        return "\n".join(f"Environment={line}" for line in lines)

    def render(self) -> str:
        argv = " ".join(self.args)
        return (
            "# Automatically generated by a2a-proxy install. Do not edit by hand.\n"
            "[Unit]\n"
            f"Description={self.description}\n"
            "After=network-online.target\n"
            "Wants=network-online.target\n"
            "\n"
            "[Service]\n"
            f"Type=simple\n"
            f"User={self.user}\n"
            f"ExecStart={self.exec_path} {argv}\n"
            "Restart={restarts}\n"
            f"RestartSec={self.restart_sec}\n"
            f"{self.environment_lines}\n"
            "\n"
            "[Install]\n"
            "WantedBy=multi-user.target\n"
        ).format(restarts=self.restarts)

    @property
    def unit_filename(self) -> str:
        return "a2a-proxy.service"
